on:
  push:
    branches: [master]
name: Deploy To Server
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest code
        uses: actions/checkout@v2
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.SERVER_FTP }}
          # server-dir: ./api_uinamfind/
          username: ${{ secrets.USERNAME_FTP }}
          password: ${{ secrets.PASSWORD_FTP }}
